name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # -----------------------------
      # Checkout Code
      # -----------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -----------------------------
      # Setup Python
      # -----------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -----------------------------
      # Install Dependencies
      # -----------------------------
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # -----------------------------
      # Run Tests
      # -----------------------------
      - name: Run Unit Tests
        run: |
          pytest

      # -----------------------------
      # Authenticate GCP
      # -----------------------------
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # -----------------------------
      # Install gcloud CLI
      # -----------------------------
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # -----------------------------
      # Configure Docker
      # -----------------------------
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # -----------------------------
      # Build Docker Image
      # -----------------------------
      - name: Build Docker Image
        run: |
          docker build \
          -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-demo-repo/fastapi-cicd-demo:latest .

      # -----------------------------
      # Push Docker Image
      # -----------------------------
      - name: Push Docker Image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-demo-repo/fastapi-cicd-demo:latest

      # -----------------------------
      # Deploy Cloud Run
      # -----------------------------
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-cicd-demo \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-demo-repo/fastapi-cicd-demo:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated